package com.revolhope.deepdev.myjavalibrary.util;

import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 * Class to provide methods to get timestamp and some other utils
 */
public class Timestamp
{
    /**
     * Static SimpleDateFormat object used in methods
     */
    private static SimpleDateFormat sdf;

    /**
     * Private constructor
     */
    private Timestamp() {}
    
    /**
     * Method to get timestamp, is generated by Calendar get millis
     * @return long Timestamp in millis
     */
    public static long now()
    {
        return Calendar.getInstance().getTimeInMillis();    
    }
    
    /**
     * Method to get formatted timestamp
     * @param format String representing the desired format
     * @return String representing timestamp in desired given format
     */
    public static String now(String format)
    {
        sdf = new SimpleDateFormat(format);
        return sdf.format(now());
    }
    
    /**
     * Method to format given timestamp to given format
     * @param timestamp Long timestamp in millis
     * @param format String representing the desired format
     * @return String formatted in given format representing the timestamp given 
     */
    public static String parse(long timestamp, String format)
    {
        sdf = new SimpleDateFormat(format);
        return sdf.format(timestamp);
    }
}
